name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure torch and other dependencies are included in requirements.txt

    - name: Run tests
      run: |
        pytest  # Ensure your tests are configured for this CI pipeline

    - name: Check torch and tensorflow installation
      run: |
        python -c "import torch; print(torch.__version__)"
        python -c "import tensorflow; print(tensorflow.__version__)"
